### ISSUE TITLE
web-based JavaScript user interface not loading

### ISSUE THREAD

**Issue by jrr-cpt** [louiejtaylor/pyViKO#4]
The web tool does not appear to be functional.
![screen shot 2018-11-08 at 10 19 28 am](https://user-images.githubusercontent.com/38894438/48211766-d2919080-e33f-11e8-8a2b-717af07f17d1.png)

**Comment by louiejtaylor** [comment]
Sorry! I lower-cased the repo name but forgot to change the link in the README. The correct one is here: http://louiejtaylor.github.io/pyviko/ . Let me know if this link works for you.

I'll also see if I can auto forward the old address to the new one.

Thank you very much for the issue!


(notes to self)
- [ ] update quick-start guide
- [ ] forward old URLs?

**Comment by jrr-cpt** [comment]
Working now! Wish I had this tool in grad school. I found it when I was looking for a tool that would count how many 1-base changes could result in an in-frame stop codon. Might be able to use for some future study.
